import type { Metadata } from "next";
import localFont from "next/font/local";

import ThemeSync from "@/components/ThemeSync";
import { WalletProvider } from "@/components/wallet";
import Cursor from "@/components/cine/Cursor";
import { ORIGIN } from "@/lib/chain";

import "./globals.css";
import "./cinematic.css";

/**
 * Both faces ship with the app, from `app/fonts`, and nothing is fetched at
 * build time or at run time.
 *
 * `next/font/google` looks equivalent and is not. It downloads each family
 * during the build, and when `fonts.googleapis.com` is unreachable it retries
 * three times and then carries on with a WARNING - so the build stays green
 * while the site quietly ships a system fallback. On a design that is almost
 * entirely typography, that is the worst possible failure: invisible in CI,
 * obvious to everyone who opens the page. It also means a build that only
 * succeeds with a warm cache, and a request to a third party on every view.
 *
 * These are the variable weight-axis faces, so one file covers the whole
 * range. `adjustFontFallback: false` because next/font has no metric override
 * table for a local face and warns on every build otherwise; the explicit
 * fallback list is what handles the swap instead.
 */
const sans = localFont({
  src: [
    { path: "./fonts/archivo-latin-wght-normal.woff2", weight: "100 900", style: "normal" },
    { path: "./fonts/archivo-latin-wght-italic.woff2", weight: "100 900", style: "italic" },
  ],
  variable: "--font-sans",
  display: "swap",
  adjustFontFallback: false,
  fallback: ["system-ui", "-apple-system", "Segoe UI", "sans-serif"],
});

const mono = localFont({
  src: [
    { path: "./fonts/jetbrains-mono-latin-wght-normal.woff2", weight: "100 800", style: "normal" },
  ],
  variable: "--font-mono",
  display: "swap",
  adjustFontFallback: false,
  fallback: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
});

export const metadata: Metadata = {
  metadataBase: new URL(ORIGIN),
  // "./" resolves against each route's own path, so every page declares itself
  // canonical rather than every page claiming to be the home page.
  //
  // This only started mattering with a real domain. `www.cachets.xyz` and
  // `cachets.xyz` serve the same pages, as does any link somebody shares with
  // a tracking parameter stapled on, and to a crawler each of those is a
  // separate document competing with the original.
  alternates: { canonical: "./" },
  title: {
    default: "Cachet - sealed proposal tendering",
    template: "%s - Cachet",
  },
  description:
    "Requests for proposals where the winning bid is chosen against criteria published before anyone bid. Criteria frozen on chain, bids sealed with a hash, and a full scorecard for every bidder.",
  applicationName: "Cachet",
  openGraph: {
    title: "Cachet - sealed proposal tendering",
    description:
      "Criteria frozen before the window opens, sealed bids, and a scorecard for every bidder rather than only the winner.",
    type: "website",
    siteName: "Cachet",
    // THE MARK, not a bespoke preview banner.
    //
    // There used to be a 1200x630 `og.png` generated by a script that existed
    // only to draw it. One picture, one generator, one more thing to keep in
    // step with a palette it duplicated. The seal is already the brand and it
    // is already in the repository as a real asset, so the preview points at
    // that instead and there is nothing left to drift.
    //
    // Square, so the card below is `summary` rather than `summary_large_image`
    // - a logo stretched into a banner slot reads as a mistake, and claiming
    // the large card without a landscape image gets it dropped entirely.
    images: [
      { url: "/brand/square-dark-512.png", width: 512, height: 512, alt: "Cachet" },
    ],
  },
  twitter: {
    card: "summary",
    title: "Cachet - sealed proposal tendering",
    description:
      "Criteria frozen before the window opens, sealed bids, and a scorecard for every bidder rather than only the winner.",
    images: ["/brand/square-dark-512.png"],
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`} suppressHydrationWarning>
      <head>
        {/*
          The theme, RESOLVED before first paint.
          "System" is turned into an explicit light or dark here rather than
          being left as an absent attribute for a media query to handle. That
          keeps the dark palette defined exactly once in globals.css: a media
          query cannot join a selector list, so the alternative is duplicating
          the whole token block, and a partial duplicate is what made "System"
          on a dark machine render light.
          Running in <head> also means a reader who chose light never sees a
          frame of dark first. Reading localStorage can throw outright when
          site data is blocked, hence the try - an unhandled error here would
          block the document.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{var t=localStorage.getItem('cachet:theme');" +
              "var d=t==='system'" +
              "?(window.matchMedia('(prefers-color-scheme: light)').matches?'light':'dark')" +
              ":(t==='light'?'light':'dark');" +
              "document.documentElement.setAttribute('data-theme',d)}" +
              "catch(e){document.documentElement.setAttribute('data-theme','dark')}",
          }}
        />
        {/*
          Whether the entry animation plays, decided before the first frame for
          the same reason the theme is.

          The intro used to switch itself on inside an effect, so the real
          sequence was: paint the landing, hydrate, THEN drop the seal animation
          on top of a page the reader was already looking at. It read as the
          animation arriving late because it was arriving late - it is meant to
          be the first thing on screen, not an interruption of the second.

          The overlay is in the server HTML now, so it is in the first paint.
          This decides synchronously whether to keep it, and CSS does the
          hiding, which is what keeps the server and client markup identical
          and the hydration quiet. Marking it seen here rather than in the
          effect matters too: the flag has to be set before a second render can
          read it.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "try{var s=sessionStorage.getItem('cachet:intro-seen')==='1';" +
              "var r=matchMedia('(prefers-reduced-motion:reduce)').matches;" +
              "if(s||r){document.documentElement.setAttribute('data-intro','skip')}" +
              "else{sessionStorage.setItem('cachet:intro-seen','1')}}" +
              "catch(e){}",
          }}
        />
      </head>
      {/* No chrome here on purpose. The two route groups bring their own: the
          cinematic route is a fixed full-viewport app, and everything else
          keeps the rule bar, header and footer. */}
      <body>
        {/*
          Global, because the rule it replaces is global.
          cinematic.css carries the handoff's `cursor:none !important` under
          `(hover:hover) and (pointer:fine)`, which is every desktop mouse on
          every page. In the handoff that is safe: the whole design is one
          page, and the custom cursor is always mounted. Here it would have
          left the docket, the forms and the docs with no pointer at all.
        */}
        <Cursor />
        {/*
          Global for the same reason as the cursor above. The boot script in
          <head> resolves the palette before the first frame and the dashboard
          toggle applies a deliberate change; this is the third case - the OS
          switching under a reader who chose "system" - and it has to work on
          every route, not only the one that happens to own the control.
        */}
        <ThemeSync />
        {/*
          One wallet state for the whole app.
          The landing's connect step and the dashboard's chip have to agree,
          and before this each component ran its own discovery: the bid panel
          could report an address while the header still offered Connect on
          the same screen.
        */}
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
